//
// Created by user on 4/7/18.
//

#ifndef PATH_CPP_PLURALSIGHT_CLASSESANDOBJECTS_H
#define PATH_CPP_PLURALSIGHT_CLASSESANDOBJECTS_H


void classesAndObjects();

#endif //PATH_CPP_PLURALSIGHT_CLASSESANDOBJECTS_H
